
paths:
  /gallery:
    get:
      tags:
        - Gallery
      summary: 제품 갤러리 조회/검색
      parameters:
        - name: region_id
          in: query
          schema:
            type: integer
            description: 지역 id
          required: true
        - name: category_id
          in: query
          schema:
            type: integer
            description: 카테고리 id
          required: true
        - name: page
          in: query
          schema:
            type: integer
            description: 페이지 번호
          required: true
        - name: keyword
          in: query
          schema:
            type: string
          required: false
      responses:
        '200':
          description: 제품 갤러리 조회/검색 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: array
                example: {
                  "products": [
                    {
                      "product_id": 2,
                      "brand_id": 1,
                      "product_name": "귀여운 양말1",
                      "brand_name": "네코",
                      "region": "서울",
                      "discount_rate": 10,
                      "price": 2000,
                      "thumbnail_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSAOnLXSaPbc4K0IId0dSTI050OfwusYAyfQzMiCF6mrwNPVdmN"
                    },
                    {
                      "product_id": 3,
                      "brand_id": 1,
                      "product_name": "귀여운 양말2",
                      "brand_name": "네코",
                      "region": "서울",
                      "discount_rate": 10,
                      "price": 2000,
                      "thumbnail_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSAOnLXSaPbc4K0IId0dSTI050OfwusYAyfQzMiCF6mrwNPVdmN"
                    }
                  ],
                  "currentPage" : 1,
                  "totalPage" : 5
                }