paths:
  /posts/{postId}/likes:
    post:
      tags:
        - Like
      summary: Like a post
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            description: The ID of the post
      responses:
        200:
          description: Successfully liked the post
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Post liked successfully"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Bad request"

  /comments/{commentId}/likes:
    post:
      tags:
        - Like
      summary: Like a comment
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
            description: The ID of the comment
      responses:
        200:
          description: Successfully liked the comment
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "Comment liked successfully"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Bad request"