
paths:
  /morelocal/letters:
    get:
      tags:
        - More Local
      summary: 로컬레터 목록 조회
      responses:
        '200':
          description: 제품 갤러리 조회/검색 성공
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 200
              message:
                type: string
                example: "success!"
              result:
                type: array
                example: {
                  "letters": [
                    {
                      "letter_id": 1,
                      "category": 0,
                      "title": "동심을 찾아주는 ~~",
                      "thumbnail_url": "https://image.png",
                      "created_date": "1970.1.1"
                    },
                    {
                      "letter_id": 2,
                      "category": 1,
                      "title": "푸른 밤의~~",
                      "thumbnail_url": "https://image.png",
                      "created_date": "1970.1.1"
                    }
                  ]
                }