paths:
  /posts:
    get:
      tags:
        - Posts
      summary: 카테고리 별 게시글 조회 로직
      parameters:
        - name: category
          in: query
          required: false
          type: string
      responses:
        '200':
          description: 게시글 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: success!
              data:
                type: array
                example: {
                  "reviewData": [
                    {
                      "post_id": 1,
                      "user_id": 1,
                      "category": "정보공유",
                      "title": "swagger-test-1",
                      "thumbnail_url": "swagger-test-1-url",
                      "content": "swagger-test-1-content",
                      "created_date": "2024.07.20",
                      "modified_date":  "2024.07.21"
                    },{
                      "post_id": 2,
                      "user_id": 1,
                      "category": "잡담",
                      "title": "swagger-test-2",
                      "thumbnail_url": "swagger-test-2-url",
                      "content": "swagger-test-2-content",
                      "created_date": "2024.07.20",
                      "modified_date":  "2024.07.21"
                    }
                  ]
                }
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.