paths:
  /users/signup:
    post:
      tags:
        - User
      summary: 사용자 등록
      parameters:
        - name: registerUser
          in: body
          required: true
          schema:
            properties:
                id:
                  type: string
                  description: 아이디
                  examples: exampleId
                email:
                  type: string
                  description: 이메일
                  example: user@example.com
                password:
                  type: string
                  description: 비밀번호
                  example: password123
                name:
                  type: string
                  description: 이름
                  example: 홍길동
                nickname:
                  type: string
                  description: 닉네임
                  example: 길동이
                phone:
                  type: string
                  description: 전화번호
                  example: 010-1234-5678
                birth:
                  type: string
                  format: date
                  description: 생년월일
                  example: 1990-01-01
                type:
                  type: string
                  description: 유저 타입(일반, 판매자)
                  example: 일반
                status:
                  type: string
                  description: 상태
                  example: active
      responses:
        201:
          description: 사용자 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: User registered successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: user@example.com
        400:
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다
        500:
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
